name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        shell: bash
        run: |
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker build . --tag ghcr.io/azoth128/cloudflare-dynamic-dns:latest
          docker push ghcr.io/azoth128/cloudflare-dynamic-dns:latest
