name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag ghcr.io/azoth128/cloudflare-dynamic-dns:latest
        run: docker push ghcr.io/azoth128/cloudflare-dynamic-dns:latest
