name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: rust:1.70

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
